### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by dudicoco** [aquaproj/aqua-installer#428]
Rather than downloading all binaries on every run it would be more efficient and faster if the action would cache the aqua binary and all of the packages binaries.

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
https://github.com/actions/cache

**Comment by suzuki-shunsuke** [comment]
aqua-installer doesn't support caching, but you can cache binaries using `actions/cache`.

e.g.

```yaml
- uses: actions/cache@v3.3.1
  with:
    path: ~/.local/share/aquaproj-aqua
    key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
    restore-keys: |
      v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
- uses: aquaproj/aqua-installer@v2.1.1
  with:
    aqua_version: v2.6.0
```

Please fix parameters properly.

e.g.

```yaml
- uses: actions/cache@v3.3.1
  with:
    path: ~/.local/share/aquaproj-aqua
    key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('.aqua/*.yaml')}} # Change key
    restore-keys: |
      v1-aqua-installer-${{runner.os}}-${{runner.arch}}-
```

It's a bit difficult to run `actions/cache` in aqua-installer because it is a bit difficult to decide parameters.

**Comment by suzuki-shunsuke** [comment]
Note that by default aqua-installer runs aqua with [-l](https://aquaproj.github.io/docs/tutorial/install-only-link) option so packages that aren't run in the workflow aren't cached.
If you want to cache all packages, please set `aqua_opts` to unset `-l` option.

```yaml
- uses: aquaproj/aqua-installer@v2.1.1
  with:
    aqua_version: v2.6.0
    aqua_opts: "" # Unset `-l` option
```

But note that if `-l` isn't set, aqua installs packages that aren't run in the workflow uselessly.

So caching of aqua-installer is more complicated than you expect.
