### ISSUE TITLE
Add the input for Node.js Support

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aqua-installer#674]
https://aquaproj.github.io/docs/reference/nodejs-support/

To execute tools installed by `npm i -g`, you need to set npm's `preset` config and the environment variable `$PATH`.
This issue proposes to add the input to set them in aqua-installer action.

e.g.

```yaml
- uses: aquaproj/aqua-installer@v3.0.1
  with:
    aqua_version: v2.30.0
    enable_nodejs: 'true'
```

```
export NPM_CONFIG_PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/npm-global" # You can change the path freely
export PATH=$NPM_CONFIG_PREFIX/bin:$PATH
```

Of course, you can configure them without this feature, but this feature is user friendly.
